# Generated by Django 2.0.5 on 2018-07-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='name2',
        ),
    ]
